Table row add rowspan function
dotnetcore/BootstrapBlazor pull request #3627
Opened 2024-06-07 08:08 UTC by startewho

##  table  add the rowspan function

### Description

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/898009/ea90c042-7448-4978-b7e1-eae18875b4c7)

2024-06-07 08:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotnetcore/BootstrapBlazor?pullRequest=3627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotnetcore/BootstrapBlazor?pullRequest=3627) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotnetcore/BootstrapBlazor?pullRequest=3627) it.</sub>

2024-06-08 09:56 UTC, ArgoZhang commented
@startewho 感谢提交 PR，请解决一下冲突，删除多余空行

2024-06-08 09:56 UTC, ArgoZhang commented on src/BootstrapBlazor.Server/Components/Samples/Table/TablesCell.razor
> +
删除空行

2024-06-08 09:56 UTC, ArgoZhang commented on src/BootstrapBlazor.Server/Components/Samples/Table/TablesCell.razor.cs
> +
删除空行

2024-06-08 09:57 UTC, ArgoZhang commented on src/BootstrapBlazor.Server/Components/Samples/Table/TablesCell.razor.cs
> +
删除空行

2024-06-08 09:57 UTC, ArgoZhang commented on src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
> +
删除一行

2024-06-08 09:57 UTC, ArgoZhang commented on src/BootstrapBlazor/Attributes/AutoGenerateColumnAttribute.cs
> +
删除两行

2024-06-08 09:58 UTC, ArgoZhang commented on src/BootstrapBlazor/Components/Table/Table.razor.Sort.cs
> +        }
不能使用内联样式

2024-06-08 09:58 UTC, ArgoZhang requested changes
代码格式化，风格统一

2024-06-09 13:43 UTC, startewho commented on src/BootstrapBlazor/Components/Table/Table.razor.Sort.cs
> +        }
我看项目里也有td使用内联的。不使用内联。放那里GetFixedCellClassString这里，如果用OnCellRender页保证不了默认样式居中

2024-06-25 07:10 UTC, merged