doc: update ListView demos
dotnetcore/BootstrapBlazor pull request #549
Opened 2023-02-18 06:55 UTC by azlis

## update ListView demos

### Description
update to new code block mode
close #548

2023-02-18 11:27 UTC, ArgoZhang requested changes
有些重复代码能否精简

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Locales/zh.json
> +  },
这些重复的是不是可以做到 Samples.ListViews 的资源文件配置项中，没必要一直重复啊

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsCollapsable.razor
> +</style>
这个重复项能否放到页面样式中

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsGroup.razor
> +</style>
这个重复项能否放到页面样式中

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsGroup.razor
> +    }
也是重复的，为了保证 CV 可行是不是可以改为 private 修饰符

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsIsAccordion.razor
> +</style>
这个重复项能否放到页面样式中

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsIsAccordion.razor
> +    }
重复类

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsNormal.razor
> +</style>
这个重复项能否放到页面样式中

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsNormal.razor
> +    }
重复类

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsPagination.razor
> +</style>
这个重复项能否放到页面样式中

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsPagination.razor
> +    }
是否可以更改为 `private class Product`

2023-02-18 11:27 UTC, ArgoZhang commented on src/BootstrapBlazor.Shared/Locales/en.json
> +  },
重复项

2023-02-18 14:56 UTC, azlis commented on src/BootstrapBlazor.Shared/Demos/ListViews/ListViewsIsAccordion.razor
> +</style>
已调整

2023-02-19 03:25 UTC, ArgoZhang approved these changes

2023-02-19 03:26 UTC, merged